### ISSUE TITLE
codec can't encode character '\u2014' 

### ISSUE THREAD

**Issue by thomascrisan** [vcalv/overdrive2opus#1] opened 2022-09-11 12:55 UTC
When running overdrive2opus, I now receive this error and don't know how to proceed.

```
WARNING:root:Guessing opus filename
Traceback (most recent call last):
  File "/usr/bin/overdrive2opus", line 487, in <module>
    encode(
  File "/usr/bin/overdrive2opus", line 395, in encode
    opus_sub = subprocess.Popen(
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1778, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2014' in position 42: ordinal not in range(256)
```

**Comment by vcalv** [comment] 2022-09-13 01:19
I'm not able to reproduce this.

Please install the most recent version (a931bd543e895979d5cc3c7ada5a86bba7f2c55e) and run again.

If the problem persists, run with `--verbose` option and attach the debug info.

**Comment by thomascrisan** [comment] 2022-09-13 15:48
The most recent version does not fix the problem but I believe I found the cause.  The "Album" tag in the .mp3 files contains the symbol:
`—`
which is character '\u2014'.  Removing this character from the .mp3 tags allows the program to complete successfully.

I suspect that the program is failing when it is reading the tags.  Unfortunately, I don't know enough python to know how to protect the program from special Latin-1 characters.


[verbose_out.txt](https://github.com/vcalv/overdrive2opus/files/9558917/verbose_out.txt)

**Comment by vcalv** [comment] 2022-09-13 20:27
I meant `--verbose` for the program, not python. You need to do something like:

`python overdrive2opus.py --verbose your_folder &>verbose_output.txt`

I really need this because I can't seem to be able to reproduce this problem, namely album names with the ` —`  character don't break anything on my system.

Thank you.

**Comment by thomascrisan** [comment] 2022-09-13 23:31
Here is the file you requested per your instructions

[verbose_output.txt](https://github.com/vcalv/overdrive2opus/files/9561424/verbose_output.txt)

**Comment by vcalv** [comment] 2022-09-16 16:20
Thank you.

I've found the problem and why I was unable to reproduce it.

You have almost certainly a locale that is not `UTF-8` compliant and therefore characters outside `latin-1` won't be supported.
Since my default locale is `en_US.UTF-8`  I was never able to reproduce the error.

**As a quick solution you can for example do:**

`LC_ALL=C.UTF-8 overdrive2opus 'your folder'`

or replace `C.UTF-8` by another locale that you have installed that supports `UTF-8`.

you can see installed locales by running `localectl  list-locales`

On my end I'll try to make tags use utf-8 encoding explicitly which is probably what makes sense.

Having locales with encodings other than `UTF-8` is a recipe for disaster in general and I strongly suggest you change that.

Thank you for all the data.

**Comment by thomascrisan** [comment] 2022-09-16 16:55
Here are my installed locales.
```
$ localectl list-locales
C.UTF-8
en_US.UTF-8
```
I don't remember why I set both ISO-8859-1 and  UTF-8 but my guess is that in the system locale-gen file contains the comments:
```
#  Examples:
#  en_US ISO-8859-1
#  en_US.UTF-8 UTF-8
#  de_DE ISO-8859-1
#  de_DE@euro ISO-8859-15
#
#  The locale-gen command will generate all the locales,
#  placing them in /usr/lib/locale.
#
#  A list of supported locales is included in this file.
#  Uncomment the ones you need.
```
I must have thought having both ISO-8859-1 and UTF-8 was a good idea for en_US.  Eliminating ISO-8859-1 solved the problem.

Running:
`LC_ALL=C.UTF-8 overdrive2opus 'your folder'`
also worked (I tested this before eliminating ISO-8859-1)

Thank you for investigating my issue.  Apologies for creating extra work for you.

**Comment by vcalv** [comment] 2022-09-16 18:06
Please update to the latest version and tell me the results when running without specifying anything about the locale.

**Comment by thomascrisan** [comment] 2022-09-17 17:52
I use yay for installations and updates.  I've attached the results of running:
`$ yay -Syu overdrive2opus-git`

The summary is:
`/usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US) `
[yay -Syu overdrive2opus-git.txt](https://github.com/vcalv/overdrive2opus/files/9592323/yay.-Syu.overdrive2opus-git.txt)

**Comment by vcalv** [comment] 2022-09-17 19:18
There mere existence of non `utf-8` locales in the system shouldn't be a problem provided they were not being used.

I suspect in your case, if you ran

`locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=
`
one of those entries would not have UTF-8 in it.

Anyway, it should be fixed now.

I'm closing this.

Feel free to reopen if needed.

**Closed as completed by vcalv** 2022-09-17 19:18 UTC

**Comment by vcalv** [comment] 2022-09-17 19:26
I also use yay and I have no issues.

The log you sent shows the package was updated, but you've messed with your locale installation. In no way does this package ever change locales.

I can't really help you with that.

The issue that existed is now fixed and should work on all systems.

My only suggestion to you is make sure you define your locale system-wide to be `en_US.UTF-8`.

I have no idea what you did that triggered that new warning on installation.
